### ISSUE TITLE
Add JSON type to fastapi-starter

### ISSUE THREAD

**Issue by andre-at-situ** [SituDevelopment/fastapi-starter#31]

**Comment by andre-at-situ** [comment]
This type is referenced in Integro-API so I thought I'd add it.

**Comment by willsawyerrrr** [comment]
The Integro API requires a JSON type to parse JSON-stringified settings for syncs and events.

However, the JSON type is not generically required for all API applications (at least not at this time). As such, I don't believe this is desired.

**Comment by andre-at-situ** [comment]
> The Integro API requires a JSON type to parse JSON-stringified settings for syncs and events.
> 
> However, the JSON type is not generically required for all API applications (at least not at this time). As such, I don't believe this is desired.

I like to think of the fastapi_starter as a great place to put any generic code to be used across all APIs. I.e. a library. If I'm authoring a library I like to think about what could be useful in future to the users of my library. I think change is a perfect example of that.

**Comment by willsawyerrrr** [comment]
Implemented by #32
